cmake_minimum_required(VERSION 3.22)
project(AZ07Loader)
set(CMAKE_CXX_STANDARD 20)
if(NOT DEFINED REPO_ROOT)
  message(FATAL_ERROR "REPO_ROOT required")
endif()
add_library(az07_loader SHARED loader.cpp)
target_include_directories(az07_loader PRIVATE "${REPO_ROOT}/module/src/main/cpp")
find_library(log-lib log)
find_library(dl-lib dl)
target_compile_options(az07_loader PRIVATE -O2 -fPIC -fvisibility=hidden)
target_link_options(az07_loader PRIVATE -Wl,--gc-sections -Wl,--strip-all)
target_link_libraries(az07_loader ${log-lib} ${dl-lib})
set_target_properties(az07_loader PROPERTIES OUTPUT_NAME "AZLoader07")
